// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Stub: run protoc --go_out=. --go-grpc_out=. proto/market.proto to regenerate.
package marketpb

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// MarketServiceClient is the client API for MarketService service.
type MarketServiceClient interface {
	GetMarket(ctx context.Context, in *GetMarketRequest, opts ...grpc.CallOption) (*MarketResponse, error)
	ListResolvableMarkets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (MarketService_ListResolvableMarketsClient, error)
	ListMarkets(ctx context.Context, in *ListMarketsRequest, opts ...grpc.CallOption) (MarketService_ListMarketsClient, error)
	UpdateMarketStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*MarketResponse, error)
}

// MarketServiceServer is the server API for MarketService service.
type MarketServiceServer interface {
	GetMarket(context.Context, *GetMarketRequest) (*MarketResponse, error)
	ListResolvableMarkets(*Empty, MarketService_ListResolvableMarketsServer) error
	ListMarkets(*ListMarketsRequest, MarketService_ListMarketsServer) error
	UpdateMarketStatus(context.Context, *UpdateStatusRequest) (*MarketResponse, error)
	mustEmbedUnimplementedMarketServiceServer()
}

// UnimplementedMarketServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMarketServiceServer struct{}

func (UnimplementedMarketServiceServer) GetMarket(context.Context, *GetMarketRequest) (*MarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarket not implemented")
}
func (UnimplementedMarketServiceServer) ListResolvableMarkets(*Empty, MarketService_ListResolvableMarketsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListResolvableMarkets not implemented")
}
func (UnimplementedMarketServiceServer) ListMarkets(*ListMarketsRequest, MarketService_ListMarketsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListMarkets not implemented")
}
func (UnimplementedMarketServiceServer) UpdateMarketStatus(context.Context, *UpdateStatusRequest) (*MarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMarketStatus not implemented")
}
func (UnimplementedMarketServiceServer) mustEmbedUnimplementedMarketServiceServer() {}

// MarketService_ListResolvableMarketsServer is the server streaming interface.
type MarketService_ListResolvableMarketsServer interface {
	Send(*MarketResponse) error
	grpc.ServerStream
}

// MarketService_ListMarketsServer is the server streaming interface.
type MarketService_ListMarketsServer interface {
	Send(*MarketResponse) error
	grpc.ServerStream
}

// MarketService_ListResolvableMarketsClient is the client streaming interface.
type MarketService_ListResolvableMarketsClient interface {
	Recv() (*MarketResponse, error)
	grpc.ClientStream
}

// MarketService_ListMarketsClient is the client streaming interface.
type MarketService_ListMarketsClient interface {
	Recv() (*MarketResponse, error)
	grpc.ClientStream
}

// RegisterMarketServiceServer registers the server implementation.
func RegisterMarketServiceServer(s grpc.ServiceRegistrar, srv MarketServiceServer) {
	s.RegisterService(&MarketService_ServiceDesc, srv)
}

// MarketService_ServiceDesc is the grpc.ServiceDesc for MarketService service.
var MarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "market.v1.MarketService",
	HandlerType: (*MarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarket",
			Handler:    _MarketService_GetMarket_Handler,
		},
		{
			MethodName: "UpdateMarketStatus",
			Handler:    _MarketService_UpdateMarketStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListResolvableMarkets",
			Handler:       _MarketService_ListResolvableMarkets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListMarkets",
			Handler:       _MarketService_ListMarkets_Handler,
			ServerStreams: true,
		},
	},
}

func _MarketService_GetMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/market.v1.MarketService/GetMarket"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetMarket(ctx, req.(*GetMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_UpdateMarketStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).UpdateMarketStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/market.v1.MarketService/UpdateMarketStatus"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).UpdateMarketStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_ListResolvableMarkets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MarketServiceServer).ListResolvableMarkets(new(Empty), &marketServiceListResolvableMarketsServer{stream})
}

type marketServiceListResolvableMarketsServer struct{ grpc.ServerStream }
func (x *marketServiceListResolvableMarketsServer) Send(m *MarketResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketService_ListMarkets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListMarketsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketServiceServer).ListMarkets(m, &marketServiceListMarketsServer{stream})
}

type marketServiceListMarketsServer struct{ grpc.ServerStream }
func (x *marketServiceListMarketsServer) Send(m *MarketResponse) error {
	return x.ServerStream.SendMsg(m)
}
