// Code generated by protoc-gen-go. DO NOT EDIT.
// Stub: run protoc --go_out=. --go-grpc_out=. proto/market.proto to regenerate.
package marketpb


// Empty is used for RPCs with no request parameters.
type Empty struct{}

func (e *Empty) Reset()         {}
func (e *Empty) String() string { return "Empty{}" }
func (e *Empty) ProtoMessage()  {}

// GetMarketRequest is the request for GetMarket RPC.
type GetMarketRequest struct {
	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
}

func (r *GetMarketRequest) Reset()         {}
func (r *GetMarketRequest) String() string { return r.MarketId }
func (r *GetMarketRequest) ProtoMessage()  {}

// ListMarketsRequest is the request for ListMarkets RPC.
type ListMarketsRequest struct {
	Status   string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Limit    int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset   int32  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (r *ListMarketsRequest) Reset()         {}
func (r *ListMarketsRequest) String() string { return "" }
func (r *ListMarketsRequest) ProtoMessage()  {}

// UpdateStatusRequest is the request for UpdateMarketStatus RPC.
type UpdateStatusRequest struct {
	MarketId  string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	NewStatus string `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
}

func (r *UpdateStatusRequest) Reset()         {}
func (r *UpdateStatusRequest) String() string { return r.MarketId }
func (r *UpdateStatusRequest) ProtoMessage()  {}

// MarketResponse is the standard market payload returned by all RPCs.
type MarketResponse struct {
	MarketId           string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Title              string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Question           string `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	ResolutionCriteria string `protobuf:"bytes,4,opt,name=resolution_criteria,json=resolutionCriteria,proto3" json:"resolution_criteria,omitempty"`
	Category           string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Status             string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	PoolAmountMinor    int64  `protobuf:"varint,7,opt,name=pool_amount_minor,json=poolAmountMinor,proto3" json:"pool_amount_minor,omitempty"`
	Currency           string `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	ClosesAt           string `protobuf:"bytes,9,opt,name=closes_at,json=closesAt,proto3" json:"closes_at,omitempty"`
	CreatedAt          string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (r *MarketResponse) Reset()         {}
func (r *MarketResponse) String() string { return r.MarketId }
func (r *MarketResponse) ProtoMessage()  {}
