// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Regen: protoc --go_out=. --go-grpc_out=. proto/settlement.proto

package settlementpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ─── Client interface ─────────────────────────────────────────────────────────

type SettlementServiceClient interface {
	GetSettlement(ctx context.Context, in *GetSettlementRequest, opts ...grpc.CallOption) (*SettlementResponse, error)
	GetUserPnL(ctx context.Context, in *GetUserPnLRequest, opts ...grpc.CallOption) (*UserPnLResponse, error)
	GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (SettlementService_GetUserPositionsClient, error)
}

type settlementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettlementServiceClient(cc grpc.ClientConnInterface) SettlementServiceClient {
	return &settlementServiceClient{cc}
}

func (c *settlementServiceClient) GetSettlement(ctx context.Context, in *GetSettlementRequest, opts ...grpc.CallOption) (*SettlementResponse, error) {
	out := new(SettlementResponse)
	err := c.cc.Invoke(ctx, "/settlement.SettlementService/GetSettlement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settlementServiceClient) GetUserPnL(ctx context.Context, in *GetUserPnLRequest, opts ...grpc.CallOption) (*UserPnLResponse, error) {
	out := new(UserPnLResponse)
	err := c.cc.Invoke(ctx, "/settlement.SettlementService/GetUserPnL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settlementServiceClient) GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (SettlementService_GetUserPositionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SettlementService_ServiceDesc.Streams[0], "/settlement.SettlementService/GetUserPositions", opts...)
	if err != nil {
		return nil, err
	}
	x := &settlementServiceGetUserPositionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SettlementService_GetUserPositionsClient interface {
	Recv() (*PositionResponse, error)
	grpc.ClientStream
}

type settlementServiceGetUserPositionsClient struct {
	grpc.ClientStream
}

func (x *settlementServiceGetUserPositionsClient) Recv() (*PositionResponse, error) {
	m := new(PositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ─── Server interface ─────────────────────────────────────────────────────────

type SettlementServiceServer interface {
	GetSettlement(context.Context, *GetSettlementRequest) (*SettlementResponse, error)
	GetUserPnL(context.Context, *GetUserPnLRequest) (*UserPnLResponse, error)
	GetUserPositions(*GetUserPositionsRequest, SettlementService_GetUserPositionsServer) error
	mustEmbedUnimplementedSettlementServiceServer()
}

type UnimplementedSettlementServiceServer struct{}

func (UnimplementedSettlementServiceServer) GetSettlement(context.Context, *GetSettlementRequest) (*SettlementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSettlement not implemented")
}

func (UnimplementedSettlementServiceServer) GetUserPnL(context.Context, *GetUserPnLRequest) (*UserPnLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPnL not implemented")
}

func (UnimplementedSettlementServiceServer) GetUserPositions(*GetUserPositionsRequest, SettlementService_GetUserPositionsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUserPositions not implemented")
}

func (UnimplementedSettlementServiceServer) mustEmbedUnimplementedSettlementServiceServer() {}

type UnsafeSettlementServiceServer interface {
	mustEmbedUnimplementedSettlementServiceServer()
}

type SettlementService_GetUserPositionsServer interface {
	Send(*PositionResponse) error
	grpc.ServerStream
}

type settlementServiceGetUserPositionsServer struct {
	grpc.ServerStream
}

func (x *settlementServiceGetUserPositionsServer) Send(m *PositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

// ─── Registration ────────────────────────────────────────────────────────────

func RegisterSettlementServiceServer(s grpc.ServiceRegistrar, srv SettlementServiceServer) {
	s.RegisterService(&SettlementService_ServiceDesc, srv)
}

func _SettlementService_GetSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlementServiceServer).GetSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/settlement.SettlementService/GetSettlement"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlementServiceServer).GetSettlement(ctx, req.(*GetSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettlementService_GetUserPnL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPnLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlementServiceServer).GetUserPnL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/settlement.SettlementService/GetUserPnL"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlementServiceServer).GetUserPnL(ctx, req.(*GetUserPnLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettlementService_GetUserPositions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetUserPositionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SettlementServiceServer).GetUserPositions(m, &settlementServiceGetUserPositionsServer{stream})
}

var SettlementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "settlement.SettlementService",
	HandlerType: (*SettlementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "GetSettlement", Handler: _SettlementService_GetSettlement_Handler},
		{MethodName: "GetUserPnL", Handler: _SettlementService_GetUserPnL_Handler},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUserPositions",
			Handler:       _SettlementService_GetUserPositions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/settlement.proto",
}
