// Code generated by protoc-gen-go. DO NOT EDIT.
// Regen: protoc --go_out=. --go-grpc_out=. proto/settlement.proto

package settlementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl   "google.golang.org/protobuf/runtime/protoimpl"
)

// ─── GetSettlementRequest ────────────────────────────────────────────────────

type GetSettlementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	MarketId      string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
}

func (x *GetSettlementRequest) Reset()         { *x = GetSettlementRequest{} }
func (x *GetSettlementRequest) String() string  { return x.MarketId }
func (x *GetSettlementRequest) ProtoMessage()  {}
func (x *GetSettlementRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetSettlementRequest) GetMarketId() string                { return x.MarketId }

// ─── SettlementResponse ──────────────────────────────────────────────────────

type SettlementResponse struct {
	state              protoimpl.MessageState
	sizeCache          protoimpl.SizeCache
	unknownFields      protoimpl.UnknownFields
	SettlementId       string `protobuf:"bytes,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	MarketId           string `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Status             string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	WinningOutcome     int32  `protobuf:"varint,4,opt,name=winning_outcome,json=winningOutcome,proto3" json:"winning_outcome,omitempty"`
	TotalPoolMinor     int64  `protobuf:"varint,5,opt,name=total_pool_minor,json=totalPoolMinor,proto3" json:"total_pool_minor,omitempty"`
	InsuranceFeeMinor  int64  `protobuf:"varint,6,opt,name=insurance_fee_minor,json=insuranceFeeMinor,proto3" json:"insurance_fee_minor,omitempty"`
	NetPoolMinor       int64  `protobuf:"varint,7,opt,name=net_pool_minor,json=netPoolMinor,proto3" json:"net_pool_minor,omitempty"`
	WinnerCount        int32  `protobuf:"varint,8,opt,name=winner_count,json=winnerCount,proto3" json:"winner_count,omitempty"`
	LoserCount         int32  `protobuf:"varint,9,opt,name=loser_count,json=loserCount,proto3" json:"loser_count,omitempty"`
	Currency           string `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	SettledAt          string `protobuf:"bytes,11,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
}

func (x *SettlementResponse) Reset()         { *x = SettlementResponse{} }
func (x *SettlementResponse) String() string  { return x.SettlementId }
func (x *SettlementResponse) ProtoMessage()  {}
func (x *SettlementResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *SettlementResponse) GetSettlementId() string      { return x.SettlementId }
func (x *SettlementResponse) GetMarketId() string          { return x.MarketId }
func (x *SettlementResponse) GetStatus() string            { return x.Status }
func (x *SettlementResponse) GetWinningOutcome() int32     { return x.WinningOutcome }
func (x *SettlementResponse) GetTotalPoolMinor() int64     { return x.TotalPoolMinor }
func (x *SettlementResponse) GetInsuranceFeeMinor() int64  { return x.InsuranceFeeMinor }
func (x *SettlementResponse) GetNetPoolMinor() int64       { return x.NetPoolMinor }
func (x *SettlementResponse) GetWinnerCount() int32        { return x.WinnerCount }
func (x *SettlementResponse) GetLoserCount() int32         { return x.LoserCount }
func (x *SettlementResponse) GetCurrency() string          { return x.Currency }
func (x *SettlementResponse) GetSettledAt() string         { return x.SettledAt }

// ─── GetUserPnLRequest ───────────────────────────────────────────────────────

type GetUserPnLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	MarketId      string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserPnLRequest) Reset()         { *x = GetUserPnLRequest{} }
func (x *GetUserPnLRequest) String() string  { return x.UserId }
func (x *GetUserPnLRequest) ProtoMessage()  {}
func (x *GetUserPnLRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetUserPnLRequest) GetMarketId() string                { return x.MarketId }
func (x *GetUserPnLRequest) GetUserId() string                  { return x.UserId }

// ─── UserPnLResponse ─────────────────────────────────────────────────────────

type UserPnLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	MarketId      string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PnlMinor      int64  `protobuf:"varint,3,opt,name=pnl_minor,json=pnlMinor,proto3" json:"pnl_minor,omitempty"`
	IsSettled     bool   `protobuf:"varint,4,opt,name=is_settled,json=isSettled,proto3" json:"is_settled,omitempty"`
}

func (x *UserPnLResponse) Reset()         { *x = UserPnLResponse{} }
func (x *UserPnLResponse) String() string  { return f(x.UserId, x.MarketId) }
func (x *UserPnLResponse) ProtoMessage()  {}
func (x *UserPnLResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *UserPnLResponse) GetMarketId() string                { return x.MarketId }
func (x *UserPnLResponse) GetUserId() string                  { return x.UserId }
func (x *UserPnLResponse) GetPnlMinor() int64                 { return x.PnlMinor }
func (x *UserPnLResponse) GetIsSettled() bool                 { return x.IsSettled }

func f(a, b string) string { return a + ":" + b }

// ─── GetUserPositionsRequest ─────────────────────────────────────────────────

type GetUserPositionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserPositionsRequest) Reset()         { *x = GetUserPositionsRequest{} }
func (x *GetUserPositionsRequest) String() string  { return x.UserId }
func (x *GetUserPositionsRequest) ProtoMessage()  {}
func (x *GetUserPositionsRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetUserPositionsRequest) GetUserId() string                  { return x.UserId }

// ─── PositionResponse ────────────────────────────────────────────────────────

type PositionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	PositionId    string `protobuf:"bytes,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MarketId      string `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	OutcomeIndex  int32  `protobuf:"varint,4,opt,name=outcome_index,json=outcomeIndex,proto3" json:"outcome_index,omitempty"`
	StakeMinor    int64  `protobuf:"varint,5,opt,name=stake_minor,json=stakeMinor,proto3" json:"stake_minor,omitempty"`
	Currency      string `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PositionResponse) Reset()         { *x = PositionResponse{} }
func (x *PositionResponse) String() string  { return x.PositionId }
func (x *PositionResponse) ProtoMessage()  {}
func (x *PositionResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *PositionResponse) GetPositionId() string              { return x.PositionId }
func (x *PositionResponse) GetUserId() string                  { return x.UserId }
func (x *PositionResponse) GetMarketId() string                { return x.MarketId }
func (x *PositionResponse) GetOutcomeIndex() int32             { return x.OutcomeIndex }
func (x *PositionResponse) GetStakeMinor() int64               { return x.StakeMinor }
func (x *PositionResponse) GetCurrency() string                { return x.Currency }
func (x *PositionResponse) GetStatus() string                  { return x.Status }
